# Use an official MongoDB image as the base image
FROM mongo:latest

# Set the working directory in the container
WORKDIR /app

# Expose the default MongoDB port (27017)
EXPOSE 27017

# Start the MongoDB server
CMD ["mongod"]